FROM gcr.io/distroless/java21-debian12:nonroot

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-XX:MaxRAMPercentage=75.0","-XX:+UseContainerSupport","-XX:+ExitOnOutOfMemoryError","-jar","/app/app.jar"]