FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7

WORKDIR /work

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY target/spring-boot-postgresql /work/application
COPY target/*.so /work/

ENV LD_LIBRARY_PATH=/work

EXPOSE 8080

USER 1001

CMD ["./application"]